name: Commercial Invoice Upload for ICO

on:
  workflow_dispatch:
  schedule:
    - cron: "7/10 * * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      KIBO_API_CREDENTIALS: ${{ secrets.KIBO_API_CREDENTIALS }}
      TIL_BIGQUERY_CREDS: ${{ secrets.TIL_BIGQUERY_CREDS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python "commercial invoice upload for ICO.py"
